### PR TITLE
lengthen frame of syndicated payday loan tool

### PR DESCRIPTION
**Pull request by Tr4pSt3R**

### CODE REVIEW

**Comment by urfolomeus** [comment]
Not sure of the context, but code is fine :+1:

**Comment by Tr4pSt3R** [comment]
thanks @urfolomeus

**Comment by darokel** [comment]
Has this been tested? Wondering if there are any responsive-y implications of updating the frame size cc @Guntrisoft

**Comment by Tr4pSt3R** [comment]
The lengthening of the iframe is exclusive to the Payday Loans Intervention tool. Other tools will not be affected.

**Comment by darokel** [comment]
I meant the Payday Loans in particular.

**Comment by Tr4pSt3R** [comment]
The only implication is an expanse between the body and the footer without text.

**Comment by darokel** [comment]
:+1:

**Pull request merged**
