### PR TITLE
[DEV APPROVED] Updating IE8 hero image css

### PR DESCRIPTION
**Pull request by johnplayer1982**
Updating hero slot bg image to use conditional @if $responsive == false { … } rather than
.ie8 & { … }

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1:

**Comment by asmega** [comment]
is this file/partial used to generate multiple css files?

**Comment by johnplayer1982** [comment]
I don't think so, @benbarnett can you confirm?

**Comment by benbarnett** [comment]
Nope just for this component, should be fine

**Comment by nmiddleweek** [comment]
:+1:

**Pull request merged**
