### PR TITLE
[DEV APPROVED] Sidebar Category Navigation

### PR DESCRIPTION
**Pull request by jriga**
**Context**
This is a combination of work between myself and @jriga, in order to add a sidebar in-category navigation which can be used on the article pages.

image

This uses the 'Collapsable' component from Dough.

The navigation contains all of the articles in the current Category, separated by Sub-Category, and will:

- Show the 'current' sub-category as expanded on page load (and before JS has been executed)
- Allow other sub-categories to be opened / closed
- Only show one sub-category open at a time

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1619)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by johnplayer1982** [comment]
:+1:

**Comment by slaywell** [comment]
Setting back to WIP as I am taking over this feature branch

**Comment by slaywell** [comment]
@tomas-stefano @johnplayer1982 - please could you both revisit this PR as there have been significant changes since you reviewed?

**Comment by tomas-stefano** [comment]
Lgtm :+1:

**Comment by johnplayer1982** [comment]
Nice :+1:

**Pull request merged**
