### PR TITLE
[DEV APPROVED] Adding Christmas opening times

### PR DESCRIPTION
**Pull request by johnplayer1982**
Updating opening times to reflect Christmas period.  Includes contact us page (en/cy) and homepage contact panels (en/cy)

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@johnplayer1982 could you add a picture or a *.gif of the changes to the PR please? 

You can use this thing that Cultivate loves using http://recordit.co/

**Comment by asmega** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by tomas-stefano** [comment]
:+1:

**Comment by johnplayer1982** [comment]
@Tr4pSt3R screenshots attached showing homepage and contact us page

contact-panels-homepage
contact-us-pages

**Comment by Tr4pSt3R** [comment]
@johnplayer1982 all the info and HTML formats are perfect! :100:

**Pull request merged**
