### PR TITLE
TP: 7311, Comment: Bumps version for Timelines

### PR DESCRIPTION
**Pull request by davidtrussler**
Required for PR#63 in Timelines (https://github.com/moneyadviceservice/timelines/pull/63)

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1453)

### CODE REVIEW

**Comment by slaywell** [comment]
Do we want to switch to the pessimistic operator `~>` rather than `>=` based on the semantic versioning / dependencies discussion we had before?

**Comment by davidtrussler** [comment]
@slaywell Probably so, more or less everything else is using that. Would that mean there is no need to bump for the "patch" iteration (i.e. ~> 1.2.0)?

**Comment by slaywell** [comment]
I *think* so, but I might be wrong. If you bundle without doing this version bump, does it pull your latest changes? I think we should change it though.

**Comment by jiannis** [comment]
@davidtrussler You are quite right, `~> x.y.z` means _"equal to or greater than the last digit_". Specifying `~> 1.2.0` in the `Gemfile` and running `bundle` would pick up versions _"equal to or greater than 1.2.0 but less than 1.3.0"_, i.e. the latest patch 1.2.x version. You'd still run `bundle` to update `Gemfile.lock` and commit that.

**Comment by jiannis** [comment]
So `~> 1.2.0` would be OK too since [timelines provides a gemspec with versions](https://github.com/moneyadviceservice/timelines/blob/master/lib/timelines/version.rb)

**Comment by davidtrussler** [comment]
@jiannis So is the best practice here to use ~> 1.2.0 in the Gemfile?

**Comment by johnplayer1982** [comment]
:+1:

**Comment by jiannis** [comment]
Squash and 👍

**Comment by slaywell** [comment]
👍

**Pull request merged**
