### PR TITLE
Update annuities landing page title tag & meta description.

### PR DESCRIPTION
**Pull request by neoeno**
image

### CODE REVIEW

**Comment by misaka** [comment]
:+1: ... yup, took a sip ... does what it sez on the tin

**Comment by ourmaninamsterdam** [comment]
:+1:

**Comment by tomas-stefano** [comment]
thumbs

**Comment by darokel** [comment]
:ship: please

**Comment by neoeno** [comment]
@darokel I want to! But we've got a question over process with Seb. Will merge as soon as I am able.

**Pull request merged**
