### PR TITLE
refactor interactors with inheritance

### PR DESCRIPTION
**Pull request by asmega**
- minor api change with exposing of id to ensure compatability

cc @tomas-stefano

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Does NewsReader require modification too?

**Comment by asmega** [comment]
it's rather different, alo looks like it's still using the old public website...

**Comment by tomas-stefano** [comment]
Yes, I am seeing this now. Yes, everything good to go. Good work mate :+1: :+1: :shipit:

**Comment by Tr4pSt3R** [comment]
nice and succinct :+1:

**Pull request merged**
