### PR TITLE
[DEV APPROVED] update action_plans from 4.0.5 to 4.0.7

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
The original PR is here: https://github.com/moneyadviceservice/action_plans/pull/131

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1458)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by jongilbraith** [comment]
👍

**Comment by Tr4pSt3R** [comment]
Thanks @jongilbraith and @tomas-stefano

**Comment by jongilbraith** [comment]
Closing this off as long forgotten and no longer needed.

action_plans is at 4.3.0 now.

**Pull request closed without merging**
