### PR TITLE
[DEV APPROVED] 7444 - SVG title attributes

### PR DESCRIPTION
**Pull request by johnplayer1982**
## Adding title attributes to SVG's

This ticket adds title attributes to the footer social SVG's.  This will also need to apply to other projects - Blog, RIO and any other that does not use the frontend footer

screen shot 2016-07-15 at 15 04 01

Please note: There is a related ticket in dough to apply the same changes to the social sharing icons:
https://github.com/moneyadviceservice/dough/pull/272

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1486)

### CODE REVIEW

**Comment by slaywell** [comment]
I might be wrong here, but I thought `role="presentation"` was for when the image is entirely decorative and should be ignored by screen readers (so each SVG either needs a title _or_  role="presentation")?

**Comment by johnplayer1982** [comment]
Yes I think you're right, These should just have titles, as they aren't just for presentation

**Comment by johnplayer1982** [comment]
@slaywell The update has been commited

**Comment by slaywell** [comment]
Tip top 👍

**Comment by davidtrussler** [comment]
Might need to add the email one as well - this is used on the articles pages, which doesn't use YouTube.

**Comment by johnplayer1982** [comment]
Thanks @davidtrussler The article social sharing icons have been updated and are in a seperate PR in dough:

https://github.com/moneyadviceservice/dough/pull/272

**Comment by davidtrussler** [comment]
👍

**Pull request merged**
