### PR TITLE
[WIP] TP: 7260, Comment: Updates regex for filtering IP addresses

### PR DESCRIPTION
**Pull request by davidtrussler**
*This is a temporary branch: this is not in the MAS codebase.*

This change updates a regex in the Optimizely testing tool that should filter IP addresses. 

The problem is that the existing one is not a regex at all but a comma-separated list of regexes and individual IP addresses. This is the file optimizely_regex_orig. 

optimizely_regex_new is the file that will replace this and is a single regex containing all the variations in the original file. 

Some useful documentation from Optimizely is here: https://help.optimizely.com/Analyze_Results/IP_Filtering:_Exclude_IP_addresses_or_ranges_from_your_results

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1478)

### CODE REVIEW

**Comment by misaka** [comment]
Good job getting this into a PR, good idea. :)

I think we should call IP RegExp bankruptcy and start from scratch, because:

- nearly half of the entries are hostnames but yet the instructions from Optimizely give us no indication that anything but an IP will work, and  common sense tells us that our website shouldn't have to do a reverse DNS lookup for every page request that hits our site just because of Optimizely
- there are also several duplicate IPs listed
- and of the remaining IPs a good number of them are ISPs (e.g. Virgin Media, Zen Internet or Pipex) so they're quite possibly temporary additions for people connecting from home

All indications that what's there currently wouldn't work at all (it's a comma-seperated list and not a RegExp) so starting from scratch won't be a regression.

**Comment by misaka** [comment]
I've broke this RegEx up to be a little bit easier to read:

```ruby
^(10\.(12\.65\.3[4-5]|254\.14\.11[0-1])|212\.28\.16\.211)$ # Old office IPs maybe? Not sure these are valid.
^109\.204\.108\.([1-6])$                # SOA ns0.easynet.co.uk
^146\.101\.166\.66$                     # SOA pri1.dns.uk.psi.net
^193\.129\.103\.78$                     # SOA ns0-01.dns.pipex.net
^193\.132\.237\.([0-9]|1[0-9]|2[0-5])$  # SOA ns0-02.dns.pipex.net
^193\.132\.237\.(1(2[2-5]))$            # SOA ns0-02.dns.pipex.net
^194\.63\.116\.72$                      # outbound1.landg.com
^194\.73\.150\.(2(2[5-7]))$             # SOA ns0.bt.net
^194\.176\.221\.149$                    # SOA ns.fjserv.net
^213\.216\.145\.236$                    # SOA infoblox-prk-grid01.ipam.cw.net
^217\.33\.241\.250$                     # SOA ns0.bt.net
^217\.156\.150\.130$                    # SOA name.phx.gblx.net
^217\.41\.71\.123$                      # host217-41-71-123.in-addr.btopenworld.com
^217\.41\.71\.123$                      # host217-41-71-123.in-addr.btopenworld.com (dup)
^46\.65\.38\.116$                       # 2e412674.skybroadband.com
^46\.65\.38\.116$                       # 2e412674.skybroadband.com (dup)
^5\.148\.140\.228$                      # Office IP
^62\.239\.159\.6$                       # SOA eddns0.bt.com
^80\.2\.103\.12$                        # 12-103-2-80.static.virginm.net
^80\.86\.41\.84$                        # SOA ns01.dns.sccis.net
^82\.69\.47\.239$                       # 82-69-47-239.dsl.in-addr.zen.co.uk
^86\.28\.73\.(4[8-9]|5[0-5])$           # 48-73-28-86.static.virginm.net
^90\.202\.83\.201$                      # 5aca53c9.bb.sky.com
^90\.202\.83\.201$                      # 5aca53c9.bb.sky.com (dup)

^/pollwidget/
^(syndicated|partner\-(tools|healthchecktool))\.moneyadviceservice\.org\.uk$
^(www\.)?(qa[0-9]{1}|dev)\.gumtree
^beta\.
^proxyprod\.
^qa\.
^staging\.
^syndi?\.moneyadviceservice\.org\.uk$
^testing\.
^www\.beta\.
^www\.gumtree\.com$
^www\.proxyprod\.
^www\.publish2\.com$
^www\.qa\.
^www\.staging\.
ecustomeropinions.com
```

**Comment by davidtrussler** [comment]
@misaka Thanks, will wait now to get confirmation of what IPs we actually need.

**Comment by pmcostello** [comment]
nice work, but we really need to cleanse this list and only include active/required exclusions, best wait to get the list of IP's we actually need then, cull the rest

**Comment by VenetiaC** [comment]
we can pull a list from GA as they are likely to be the same - it is certainly a good starting point.  Red-eye have also confirmed that it needs to be IPs only and not hostnames in the Regex

**Comment by seane** [comment]
Here's a list manually culled from our GA platform Filter list: https://analytics.google.com/analytics/web/#management/Settings/a4205932w8099795p61569629/%3Fm.page%3DFilters%26m-content-filterByProfileTable.rowShow%3D50%26m-content-filterByProfileTable.rowStart%3D0%26m-content-filterByProfileTable.sortColumnId%3Drank%26m-content-filterByProfileTable.sortDescending%3Dfalse%26m-content.mode%3DEDIT%26m-content.filterId%3D23438775/

[MAS GA IP Address Exclusions.xlsx](https://github.com/moneyadviceservice/frontend/files/331630/MAS.GA.IP.Address.Exclusions.xlsx)

**Comment by davidtrussler** [comment]
optimizely_regex_new now updated to exclude unnecessary IP addresses and all hostnames.

**Comment by davidtrussler** [comment]
Just to be clear: optimizely_regex_new will be aded to the configuration in the Optimizely tool, it is not part of the MAS codebase. It will then be tested there to ensure it is blocking the required IP addresses. We just need to test there that the regex is syntactically correct.

**Comment by Tr4pSt3R** [comment]
@davidtrussler you can use http://rubular.com to verify the syntactic validity of the optimizely regex.

**Comment by misaka** [comment]
Much neater. A couple of suggestions though:

- change the office IP to a range: `^5\.148\.140\.228$` -> `^5\.148\.140\.2(2[5-9]|3[0-8])$`
- add the IPs of our assets in Azure: `^10\.2[0-3](\.\d{1,3}){2}$`

**Comment by davidtrussler** [comment]
I have made the suggested additions from @misaka above.

**Comment by rnalexander** [comment]
Assigning this as WIP until we get a chance to talk about it in standup and find out what's going on as this has now become confusing.

**Comment by davidtrussler** [comment]
To clarify the status of this ticket (because it's not a standard PR, I just wanted to put it through that process to get developer input):
- all debt (clarifying from MAS and RedEye what IPs are actually required and from RedEye what formats are acceptable) is now cleared
- it still needs thumbs to check from a developer perspective that the RegEx is OK
- it will be tested by RedEye via the Optimizely tool and not in any of our environments

**Comment by misaka** [comment]
:+1:

**Comment by davidtrussler** [comment]
This PR is being closed: it was a temporary branch created to discuss some work not to be added to codebase.

**Pull request closed without merging**
