### PR TITLE
[DEV APPROVED] - Adds WPCC to the Syndication tool list

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
**Target Process ticket**: [TP#8227](https://moneyadviceservice.tpondemand.com/entity/8227)

**Summary**
Adds WPCC to the list of syndicated tools.

**Checklist**
- [x] Tests passed.
- [x] Code Climate passed for this PR.
- [x] Commit history reviewed (clear commit messages).

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1819)

### CODE REVIEW

**Comment by margOnline** [comment]
👍

**Comment by tomas-stefano** [comment]
👍

**Comment by Tr4pSt3R** [comment]
@willhall88 @margOnline @tomas-stefano I have made a change to the syndication PR which was approved earlier. I had to remove the old WPCC details which was obstructing the new tool from working properly. Rather than opening a new PR I added it to this one. Is that okay, please? 

Please review it again, if you are okay with adding more work to an already approved PR. 
If it's not okay then let me know and I will create a new PR for this.

**Comment by willhall88** [comment]
👍

**Comment by tomas-stefano** [comment]
But what it was exactly obstructing on the new to work properly? Can you add your findings on the PR description (or the commit messages), please?
And ... this change represents the old wpcc syndication will be removed in favour of the new one. Is the product/partnership team ok with it? And should we have a redirect from the old syndication to the new?

**Comment by Tr4pSt3R** [comment]
@tomas-stefano this was obstructing because we are using the same `id` to pick up the widgets within the Test Harness configurations. 

## WPCC English Widget Config
```
#file: widgets/workplace_pensions.html

---
layout: widget
widget:
  id: workplace_pensions
  name: "Workplace Pensions Contributions Calculator"
  url: "/en/tools/workplace-pension-contribution-calculator"
  lang: en
---
{% include widget.html %}
```

## WPCC Welsh Widget Config
```
#file: widgets/workplace_pensions_cy.html

---
layout: widget
widget:
  id: workplace_pensions
  name: "Workplace Pensions Contributions Calculator"
  url: "/cy/tools/cyfrifiannell-cyfraniadau-pensiwn-gweithle"
  lang: cy
---
{% include widget.html %}
```

**Comment by tomas-stefano** [comment]
Can we sit down together after lunch to discuss and see in more details this problem, please? Wdyt?

**Comment by Tr4pSt3R** [comment]
@tomas-stefano ready when you are? I have spoken to Edmund(Project Manager) and Dobrin(Partnership Executive) they are happy to replace the old tool with the new. Is there any reservations in particular that you have, please??

**Comment by Tr4pSt3R** [comment]
comments

Hi @tomas-stefano I have just seen these comments from Edmund here in lieu with a conversation with Dobrin. I have spoken to Ed and he has confirmed that it will be advisable to retain the syndicated version of the old tool whilst creating the new. 

Everything has been restored to what it was. Have a look at the PR again. If you are pleased with it just tag the title with [DEV APPROVED].

**Comment by willhall88** [comment]
👍 ->👎->  👍 👍  ¯\_(ツ)_/¯

**Comment by tomas-stefano** [comment]
Ok, now everything is good 👍 .

**Comment by Tr4pSt3R** [comment]
Thanks @willhall88 @tomas-stefano @margOnline

**Pull request merged**
