### PR TITLE
[DEV APPROVED] Add extra class to category element if more than 5 subcategories

### PR DESCRIPTION
**Pull request by jongilbraith**
Attn @davidtrussler 🙂

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1640)

### CODE REVIEW

**Comment by davidtrussler** [comment]
👍 Cheers!

**Comment by tomas-stefano** [comment]
:+1:

**Comment by johnplayer1982** [comment]
:+1:

**Comment by jongilbraith** [comment]
Cheers all!

**Pull request merged**
