### PR TITLE
[DEV APPROVED] 7333 - Removing newsletter signup in footer

### PR DESCRIPTION
**Pull request by johnplayer1982**
This is a recreation of an earlier ticket that was already thumbed,  rebase gone wrong meant re-do’ing, this is already on QA, apologies

Original PR Description

## 7333 - Removing Newsletter signup from Footer

As per [ticket 7333 in TP](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=E9844BE5A953DC8AF06B0B23D5B7DBA0#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==) Removing the newsletter signup option from the footer.

- Removing markup
- Removing partials
- Removing CSS
- Removing tests for this component

There will be an additional ticket on CMS to remove the editable section from the footer

| Desktop |
|------------|
|screen shot 2016-05-18 at 12 10 01|

| Mobile |
|----------|
|screen shot 2016-05-18 at 12 10 15|

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1457)

### CODE REVIEW

**Comment by davidtrussler** [comment]
👍

**Comment by Tr4pSt3R** [comment]
Hey @johnplayer1982 there are some more dusty pipe works to be done :)
Have a look below for details. 

```
 () ~/Projects/frontend-0 (7333-removing-footer-newsletter)
⤷  ack Newsletter lib/
lib/core/entity/footer.rb
10:      @newsletter ||= Core::Newsletter.new(newsletter_options)

lib/core/entity/newsletter.rb
2:  class Newsletter

lib/core/entity/newsletter_subscription.rb
2:  class NewsletterSubscription

lib/core/interactor/newsletter_subscription_creator.rb
2:  class NewsletterSubscriptionCreator
6:      @subscription = NewsletterSubscription.new(email: email)

lib/core/repository/newsletter_subscriptions/cream.rb
2:  module NewsletterSubscriptions

lib/core/repository/newsletter_subscriptions/fake.rb
2:  module NewsletterSubscriptions

lib/core.rb
24:  autoload :Newsletter, 'core/entity/newsletter'
27:  autoload :NewsletterSubscription, 'core/entity/newsletter_subscription'
56:  autoload :NewsletterSubscriptionCreator, 'core/interactor/newsletter_subscription_creator'
140:    module NewsletterSubscriptions

lib/newsletter_exclusions.rb
1:module NewsletterExclusions
```

**Comment by johnplayer1982** [comment]
@Tr4pSt3R There is still a newsletter signup box on the [contact us page](https://www.moneyadviceservice.org.uk/en/corporate/contact-us),  At the point where the last newsletter signup is removed, the back end code will also be removed, If we do it in this PR, the contact us page signup will error.  This is just to remove the UI of the signup in the footer

**Comment by Tr4pSt3R** [comment]
okay just checking ::)

👍 👍

**Pull request merged**
