### PR TITLE
[DEV APPROVED] - 8900 Remove action plans

### PR DESCRIPTION
**Pull request by gotbadger**
**Target Process ticket**

[TP 8900](https://moneyadviceservice.tpondemand.com/entity/8900-remove-depricated-actionplan-controller-from-frontend)

**Summary**
This dead code was making it hard to progress on implementing the Mas CMS gem. This PR removes ActionPlans controller and core objects from frontend.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Good! Should this files be removed as well?

features/support/world/action_plans.rb
features/support/ui/pages/action_plan.rb
Steps which mention features/step_definitions/primary_navigation_steps.rb
features/cassettes/www_moneyadviceservice_org_uk/get/en/news_jsonlimit_10_page_number_1.yml

**Comment by gotbadger** [comment]
First 2 sound likely. Will look into this. 

Its quite hard to get everything so if you have any other ideas suggest away!

**Comment by tomas-stefano** [comment]
Just this and looks good to me after.

**Comment by gotbadger** [comment]
@willhall88 / @tomas-stefano managed to find a whole bunch of unused feature spec stuff so have removed it all check 55cb331 to see what i removed

**Comment by willhall88** [comment]
nice one

**Pull request merged**
