### PR TITLE
TP-6297: Updating dough-ruby gem version

### PR DESCRIPTION
**Pull request by Guntrisoft**

### CODE REVIEW

**Comment by benbarnett** [comment]
:+1:

**Comment by jonalport** [comment]
:+1:

**Comment by Guntrisoft** [comment]
strange - I only did bundle update dough-ruby ...?

**Comment by benbarnett** [comment]
I just did it `bundle update dough-ruby` on master (before this was merged) and rack got updated too.

**Comment by neoeno** [comment]
`bundle update dough-ruby` is allowed to update all gems that `dough-ruby` depends on. In this case, dough-ruby depends on rails which depends on actionpack which depends on rack.

**Comment by darokel** [comment]
Yeah I generally use `bundle update --source gemname` first. Just tried it now and only `dough-ruby` was updated. Here's some more info on the difference http://ilikestuffblog.com/2012/07/01/you-should-update-one-gem-at-a-time-with-bundler-heres-how/

**Pull request merged**
