### PR TITLE
Tp 11850 accessin link

### PR DESCRIPTION
**Pull request by thenapking**
[TP-11850](https://maps.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRDU5MDREQTBBMjZDQUJFRDEyQkFEMkQwMEU5RjJDQzkifQ==&boardPopup=userstory/11850/silent)

Remove logo and accessin link.  Replace with mailto link.  
Add simple test on footer partial.

### CODE REVIEW

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/11850

**Review by davidtrussler — CHANGES_REQUESTED** [review]
Could we not commit the changes to `Gemfile.lock` as part of this work? Otherwise looks good - happy to approve when that is looked at.

**Comment by thenapking** [comment]
> Could we not commit the changes to `Gemfile.lock` as part of this work? Otherwise looks good - happy to approve when that is looked at.

Of course.  TBH I am not sure why those changes are there - I think my master branch must be dirty from when I first tried to get the repo going.

**Review by davidtrussler — APPROVED** [review]
LGTM! 👍

**Review by ladamsatmaps19 — APPROVED** [review]
Yes this mailbox has been created with yourself and the requested colleagues having delegated access.

Thanks Tom!

**Comment by thenapking** [comment]
Now deployed to production

**Pull request closed without merging**
