### PR TITLE
[WIP] - Ruby and Rails Upgrade

### PR DESCRIPTION
**Pull request by darokel**
Yup, this is going to be a meaty one. Thought I'd kick this off as I think it's about time we upgrade this bad boy. Below is a progress tracker of what we need to update, please feel free to add/remove as necessary.

# Goals

- Ruby 2.2.2
- Rails 4.2.1

# Progress

- [ ] Bump Ruby version
- [ ] Bump Rails version

### Engines/Gems to be updated

- [ ] Advice plans
- [ ] Agreements
- [ ] Budget planner
- [ ] Car cost tool
- [ ] Debt advice locator
- [ ] Debt free day calculator
- [ ] Decision trees
- [x] Dough
- [x] Feedback
- [ ] Mortgage calculator
- [ ] Pensions calculator
- [X] Quiz
- [ ] Rio
- [ ] Savings calculator
- [x] Timelines

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/911)

### CODE REVIEW

**Comment by asmega** [comment]
Struggling to update Debt advice locator. It needs to use master of geokit-rails which has a fix for rails 4.2 as there was a breaking changed in Arel. However there is no gem release.

Not sure if we want to build master and push to our own gem server or let the host app point to the git repo using the master branch?

**Comment by darokel** [comment]
I think it may be best to point to the git repo using the master branch for now, at least until the branch has been merged. What do you think? @asmega

**Comment by asmega** [comment]
Sure, either way is good for me

**Comment by neoeno** [comment]
@asmega @darokel Had a go at debt-advice-locator ^^^ :simple_smile:

**Comment by darokel** [comment]
@neoeno Awesome! Will try and give this update another crack when I get a minute

**Comment by benlovell** [comment]
Rails is at 4.2.1 and Ruby is at 2.2.2 now. :wink:

**Comment by darokel** [comment]
@benlovell Yeah thanks for the heads up :)

**Comment by darokel** [comment]
Just a quick update on this PR: I will get around to sorting out the upgrade soon. All the core tools listed above have now been updated.

**Comment by darokel** [comment]
Update: Think it's about time we get this in, I'll take a look at it this week.

**Comment by darokel** [comment]
@mas-development-team What are you guys waiting for, get this merged in! 😄

**Comment by Tr4pSt3R** [comment]
@darokel i think it's gone under the radar because it's prefixed with [WIP]. It never gets pick up by Masbot so it never gets our attention.

**Comment by pmcostello** [comment]
👎 this can't be merged into master as a bunch of existing frontend gems will break as they depend on Rails 4.1, namely quiz and timelines

**Comment by pmcostello** [comment]
timelines gem is currently pinned to Rails 4.1.8

**Comment by tomas-stefano** [comment]
I agree with @darokel. But  I renamed to WIP since there are gems that need to be handled. And I will talk with Ed (the P.O) explaining the impact of this PR so he can prioritize this on the backlog.

**Comment by jongilbraith** [comment]
Closing in favour of https://github.com/moneyadviceservice/frontend/pull/1549

**Pull request closed without merging**
