### PR TITLE
add summer budget promo

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by rnalexander** [comment]
:+1:

**Comment by Guntrisoft** [comment]
The jpeg isn't optimised

**Comment by Guntrisoft** [comment]
I'll send you an optimised one @asmega on slack

**Comment by asmega** [comment]
what do you use to optimize it? i use `optipng` for pngs

**Comment by Guntrisoft** [comment]
jpgs recently i've used http://www.jpegmini.com/

**Comment by Guntrisoft** [comment]
Also for complete reference - I use http://pngcrush.com/ for PNGs and https://jakearchibald.github.io/svgomg/ for SVGs :)

**Comment by asmega** [comment]
surely there must be a command line tool for jpegs instead of relying on a third party service?

**Comment by Guntrisoft** [comment]
I'm sure there is, this is more for the one offs, rather than build process - we should have this built in really.

**Comment by asmega** [comment]
regardless for one-offs or automation there should still be a command line tool!

but yes agreed this should be automated somehow. i'm thinking i should have global pre-commit hook

**Comment by asmega** [comment]
@Guntrisoft it's now been optimised and rebased

**Comment by Guntrisoft** [comment]
:+1:

**Pull request merged**
