### PR TITLE
[DEV APPROVED] Add email templates for BudgetPlanner decommission

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
[Card 7854](https://moneyadviceservice.tpondemand.com/entity/7854)

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1645)

### CODE REVIEW

**Comment by johnplayer1982** [comment]
👍

**Comment by tomas-stefano** [comment]
Sorry, but I didn't understand this PR. Did you already added a PR on budget planner about this subject? Why it needs here?

**Comment by Tr4pSt3R** [comment]
@tomas-stefano the PR on the BudgetPlanner is the actual email template that will be sent out. The PR on _frontend_ is for viewing the English and Welsh versions online as we only send out an English version.

**Comment by tomas-stefano** [comment]
Ok. So lgtm :+1:

**Pull request merged**
