### PR TITLE
[DEV APPROVED]Adding warning tools 7047

### PR DESCRIPTION
**Pull request by slaywell**
This PR adds a warning to the Redundancy Pay Calculator that will automatically appear on the 16th March.

image

image

### CODE REVIEW

**Comment by nmiddleweek** [comment]
Looks good... Quick one... Do the left and right margins match the design?… I can’t see without opening up the branch and ENV is busted at the moment.

**Comment by slaywell** [comment]
@nmiddleweek they do now! New screenshots in the PR description.

**Comment by johnplayer1982** [comment]
:+1: Nice one!

**Comment by nmiddleweek** [comment]
:+1:

**Comment by rnalexander** [comment]
Looks good :+1:

**Pull request merged**
