### PR TITLE
Remove Sticky Footer from survive january campaign.

### PR DESCRIPTION
**Pull request by nmiddleweek**

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
Although, it should be tested. This "Survive January" will be removed after January right?

**Comment by johnplayer1982** [comment]
:+1:

**Comment by slaywell** [comment]
@Tr4pSt3R Yes - it will be removed. We will get a ticket added to the backlog.

**Pull request merged**
