### PR TITLE
[DEV APPROVED] 7334 remove newsletter sticky footer

### PR DESCRIPTION
**Pull request by davidtrussler**
This PR removes the sticky footer newsletter sign-up component on all pages, plus
- associated tests
- styles specific to the component
- cookie setting/getting functionality specific to the sticky newsletter
- the logic that excludes certain content from showing the component

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1456)

### CODE REVIEW

**Comment by slaywell** [comment]
Tested locally - looking good. I think there might be a few extra things we can chop - I searched the whole repo for 'sticky' which found a few references to the sticky footer within  `/frontend/features/support/ui/` which I think we can remove.

E.g. `/features/support/ui/sections/sticky_newsletter.rb`?

**Comment by tomas-stefano** [comment]
I think this should be deleted too: https://github.com/moneyadviceservice/frontend/blob/master/app/helpers/application_helper.rb#L54
https://github.com/moneyadviceservice/frontend/blob/master/app/views/shared/_header.html.erb#L2
https://github.com/moneyadviceservice/frontend/blob/master/app/assets/stylesheets/layout/common/_header.scss#203

**Comment by tomas-stefano** [comment]
And https://github.com/moneyadviceservice/frontend/blob/master/spec/helpers/application_helper_spec.rb#L2

**Comment by davidtrussler** [comment]
We need those first three, which are for the sticky header on mobile.

**Comment by tomas-stefano** [comment]
Yes, you're right. Looking to the project I can find anything related to stick footer. So 👍

**Comment by slaywell** [comment]
👍

**Pull request merged**
