### PR TITLE
[DEV APPROVED] id: 6904, comment: updates version of Budget Planner for changes to S…

### PR DESCRIPTION
**Pull request by davidtrussler**
…ocial Sharing changes

- Refers to https://github.com/moneyadviceservice/budget_planner/pull/392

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
Hi @davidtrussler could you reference the Budget Planner changes PR that warrants this PR please? Just for reference and for quick checks

**Comment by urfolomeus** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
@davidtrussler this references an old PR?

**Comment by Tr4pSt3R** [comment]
That's the right one :dancer: 
:+1:

**Pull request merged**
