### PR TITLE
unfork feature gem and use maintained version

### PR DESCRIPTION
**Pull request by asmega**
cc @darokel

### CODE REVIEW

**Comment by darokel** [comment]
I think Steve did some extra work in our own fork to get multiple features working which is why it was pointed to a branch.

**Comment by asmega** [comment]
it got merged in https://github.com/mgsnova/feature/pull/22

**Comment by darokel** [comment]
Ah sweet 👍🏼

**Comment by Tr4pSt3R** [comment]
:+1: sweet :cherries:

**Comment by rnalexander** [comment]
:+1:

**Pull request merged**
