### PR TITLE
Timelines update

### PR DESCRIPTION
**Pull request by esbel**
Adding timelines engine (moving it from `public_website` repository).

Version specified to be at least 1.2.0.

### CODE REVIEW

**Comment by benlovell** [comment]
I'd maybe add a routing spec, just as a sanity check this gets mounted correctly. There are examples of this already for some of the existing engines.

**Comment by esbel** [comment]
@benlovell I'll do it.

**Comment by tomas-stefano** [comment]
@esbel LGTM :+1:

**Comment by benlovell** [comment]
:+1:

**Pull request merged**
