### PR TITLE
8461 Bump Debt Advice Locator to 2.5.0

### PR DESCRIPTION
**Pull request by gotbadger**
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8461)

Also updates tools.js to include new cut-down (face-to-face only) syndicated version of debt advice locator (see https://github.com/moneyadviceservice/debt-advice-locator/pull/120).

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1785)

### CODE REVIEW

**Comment by igelstorm** [comment]
:+1:

**Comment by willhall88** [comment]
👍

**Comment by norm** [comment]
That's two logical independent changes (bump version, update tools.js), so I think that should be reflected by being two commits not one.

**Comment by igelstorm** [comment]
@norm Fair point. Done.

**Pull request merged**
