### PR TITLE
Internal server error fix

### PR DESCRIPTION
**Pull request by tomas-stefano**
There are some tools that are returning server error and not rendering the custom error page. e.g: https://www.moneyadviceservice.org.uk/cy/agreements/partners/new

After investigate, I opened this PR. I explained the problem on the commit itself.

### CODE REVIEW

**Comment by asmega** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1: nice one @tomas-stefano

**Comment by Tr4pSt3R** [comment]
Just to add, @tomas-stefano it is, however, not ready to be merge with `master` as the cucumber and specs are failing. I am investigating it. I will let you know of my findings

**Comment by tomas-stefano** [comment]
The rspec tests are passing here. The cucumber I will check.

**Comment by tomas-stefano** [comment]
@asmega and @Tr4pSt3R all tests passing. Can you review again, please?

**Comment by asmega** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Pull request merged**
