### PR TITLE
[DEV APPROVED] - 8278 - Show Money Manager in user's "Saved Tools"

### PR DESCRIPTION
**Pull request by igelstorm**
**Target Process ticket**

https://moneyadviceservice.tpondemand.com/restui/board.aspx?acid=13857292912bd09b911bf771e091f219#page=userstory/8278

**Summary**
For a user who has completed the Money Manager questionnaire, show Money Manager in the Saved Tools section of My Account.

**Examples (optional)**
screen shot 2017-06-16 at 12 12 53

**Checklist**

Make sure that when your PR is good to be reviewed you check the below checks:

+ [x] Tests passed.
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Code Climate passed for this PR.
+ [x] Commit history reviewed (clear commit messages).

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1752)

### CODE REVIEW

**Comment by igelstorm** [comment]
I'm not sure what to make of the fact that codeclimate is failing with new issues - the issues listed seem unrelated to the changes in this PR. Does anyone know why this might happen?

**Comment by tomas-stefano** [comment]
The issues on Code Climate (the only issue that I am seeing at the moment) is related to **the page objects on features folder** (the cucumber specs). I would ignore the cucumber code since the goal of Code Climate is to scan through the app not the tests. You can see more details here:  https://docs.codeclimate.com/v1.0/docs/excluding-files-and-folders

**Comment by tomas-stefano** [comment]
By the way the PR code is awesome. 👍 👍 (after seeing the CodeClimate statement above)

**Comment by margOnline** [comment]
This looks good. I think there is an opportunity to partialise the edit view - wdyt?

**Comment by igelstorm** [comment]
@margOnline Good call - we've partialised the 'Your Tools' section.

**Comment by margOnline** [comment]
Thanks @igelstorm. Wdyt about a bit more partialising in that view so it ends up something like
```
<%= render 'your_tools' %>
```

**Comment by igelstorm** [comment]
Agreed @margOnline - that's done. :+1:?

**Comment by margOnline** [comment]
lgtm 👍

**Pull request merged**
