### PR TITLE
[DEV APPROVED] 11404 static coronavirus hub page

### PR DESCRIPTION
**Pull request by davidtrussler**
[TP11404](https://maps.tpondemand.com/entity/11404-static-coronavirus-hub-page)

This creates a new content hub page to draw together all our content on Coronavirus. It is based on previous implementations of this model (e.g. '[Managing your fee-free basic bank account](https://www.moneyadviceservice.org.uk/en/hub/bank_accounts)') though for this work a couple of new block modules have been created and the styles have been updated a little to improve the layout for the new content.

### CODE REVIEW

**Comment by davidtrussler** [comment]
@andreferreiradlw @akenzua I just added a small commit to this PR. Can (maybe just one of) you have a quick look by way of sanity check? 

The language link was misbehaving because the `alternate_slug` value was being set at too generic a level, i.e. it was referencing content hubs in general. It now references the specific one we're on. 

I'm going to redeploy this to test in the meantime anyway.

**Comment by akenzua** [comment]
@davidtrussler, its showing this error page now:
coronavirus_hub

**Comment by davidtrussler** [comment]
> @davidtrussler, its showing this error page now:
> coronavirus_hub

Can you see if this is related to this PR? Is it only an issue on this branch? I can't replicate it.

**Comment by akenzua** [comment]
I think its from my end. Getting the same on master.

**Pull request merged**
