### PR TITLE
Update db/schema.rb

### PR DESCRIPTION
**Pull request by tomas-stefano**
I just did rake db:schema:load && rake db:migrate. Nothing else. 

This is failing on CI here: https://go.test.moneyadviceservice.org.uk/go/pipelines/responsive_commit/2013/test_and_build/2

Because this PR: #1225 that the schema.rb (schema version) was not commited.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
@asmega Can you check if everything is fine, please? See the description.

**Comment by darokel** [comment]
You may need to run `rake db:schema:load` first

**Comment by tomas-stefano** [comment]
Yes, it is true. Thanks! Now everything good to go.

**Comment by rnalexander** [comment]
OK, this works on my local machine and the cucumber tests.  I'm going to merge and run it.

**Pull request merged**
