### PR TITLE
May Bank Holiday opening hours update

### PR DESCRIPTION
**Pull request by ourmaninamsterdam**
@moneyadviceservice/team-bee

### CODE REVIEW

**Comment by ourmaninamsterdam** [comment]
Good call on the refactor. Will get @ALiaume to add it to the backlog.

I cannot see any related tests failing. The ones that did fail look like environment issues. Can you confirm?

```
rspec ./spec/routing/landing_pages_spec.rb:17 # Static page routing /tools/annuities when the feature flag is disabled does not route
rspec ./spec/features/html_validation_spec.rb:37 # HTML validation article pages in English should have valid HTML
rspec ./spec/features/html_validation_spec.rb:42 # HTML validation article pages in Welsh should have valid HTML
rspec ./spec/features/html_validation_spec.rb:52 # HTML validation search results in English with no query should have valid HTML
rspec ./spec/features/html_validation_spec.rb:66 # HTML validation search results in English with results should have valid HTML
rspec ./spec/features/html_validation_spec.rb:57 # HTML validation search results in English with no results should have valid HTML
rspec ./spec/features/html_validation_spec.rb:75 # HTML validation search results in Welsh with no query should have valid HTML
rspec ./spec/features/html_validation_spec.rb:89 # HTML validation search results in Welsh with results should have valid HTML
rspec ./spec/features/html_validation_spec.rb:80 # HTML validation search results in Welsh with no results should have valid HTML
rspec ./spec/features/html_validation_spec.rb:24 # HTML validation category pages in English should have valid HTML
rspec ./spec/features/html_validation_spec.rb:30 # HTML validation category pages in Welsh should have valid HTML
rspec ./spec/requests/tool_integration/rio_spec.rb:11 # RIO /en/retirement-income-options
rspec ./spec/requests/tool_integration/rio_spec.rb:11 # RIO /cy/opsiynau-incwm-ymddeoliad
```

**Comment by asmega** [comment]
:+1:  Those failures are intermittent as one of the boxes is missing a dependency which has not been resolved.

**Comment by darokel** [comment]
:+1:

**Comment by seane** [comment]
@darokel Not sure what the model is going forward...might be a new provider down the line who will be open at different times. But for now...

**Pull request merged**
