### PR TITLE
7573 update cost calculator builder parent layout lookup

### PR DESCRIPTION
**Pull request by jongilbraith**
A cleanup task in preparation for implementing the standalone cost calculator builder.

The now standardised convention is for the tool to call `parent_template` which is a helper that should be defined in one of the parent controllers obtained from the mounting application.

The cost calculator builder has been updated to call `parent_template` in https://github.com/moneyadviceservice/cost_calculator_builder/pull/71 and this change implements the logic to make the selection instead.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1565)

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
You may want to remove the preceding 'WIP' from the title for this commit comment ```WIP - bump cost_calculator_builder gem (cfa927d)```

Other than that, all is good. 
👍

**Comment by jriga** [comment]
👍

**Comment by tomas-stefano** [comment]
👍 (after reword the WIP commit)

**Comment by jongilbraith** [comment]
@Tr4pSt3R @tomas-stefano "well duh"

**Pull request merged**
