### PR TITLE
[DEV APPROVED] Updating Hero CSS

### PR DESCRIPTION
**Pull request by johnplayer1982**
Updating Hero slot CSS, removing references to images as they will be served inline from CMS.

### CODE REVIEW

**Comment by johnplayer1982** [comment]
full width
posh tablet
budget tablet
fancy hi res phone
my cheap phone

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by slaywell** [comment]
:+1: 

@johnplayer1982 as discussed let's keep the double-density version of the image in the CMS and add an alternative layout for IE8.

**Comment by asmega** [comment]
:+1:

**Pull request merged**
