### PR TITLE
[DEV APPROVED] Add JQuery-migrate configuration to test-main

### PR DESCRIPTION
**Pull request by MarcoBgn**
**Target Process ticket**
[Tp Card](https://moneyadviceservice.tpondemand.com/entity/9754-update-jquery-in-frontend-application)

**Summary**

- In order to ensure the usage of JQuery migrate in Karma specs, explicit
  config has been added to: 
  - karma.conf 
    - -> correct JQuery version
  - test-main
    - -> Jquery source path and Wrapper
    - -> Shim entries for jquery and migrate 

**Checklist**

Make sure that when your PR is good to be reviewed you check the below checks:

+ [x] Tests passed.
+ [x] Code Climate passed for this PR.
+ [x] Commit history reviewed (clear commit messages).

### CODE REVIEW

**Comment by nmiddleweek** [comment]
Looks good 👍

**Comment by nmiddleweek** [comment]
Howabout we approve this into Preview and then could rebase 9754_Update-JQuery-3.3.1 from Preview to collate everything together and keep the history? Would that work for you?

**Comment by nmiddleweek** [comment]
I've just checked this by switching the bases of this PR... "9754_Update-JQuery-3.3.1" seems to be out of the date with "Preview" and could do with a git rebase anyway.

**Comment by davidtrussler** [comment]
> I've just checked this by switching the bases of this PR... "9754_Update-JQuery-3.3.1" seems to be out of the date with "Preview" and could do with a git rebase anyway.

Yes it would be out of date because there's been another deploy. There aren't any conflicts though so that won't be a problem.

**Comment by davidtrussler** [comment]
Sorry - didn't mean to close that PR. Just reopened it!

**Comment by MarcoBgn** [comment]
Closing as not relevant anymore in the current state

**Pull request closed without merging**
