### PR TITLE
TP12006 - TP12005 - TP12007 - Rebrand Registration Screens

### PR DESCRIPTION
**Pull request by andreferreiradlw**
[TP12006](https://maps.tpondemand.com/entity/12006-rebrand-register-screen-on-budget-planner)
[TP12007](https://maps.tpondemand.com/entity/12007-rebrand-forgot-your-password-screen)
[TP12005](https://maps.tpondemand.com/entity/12005-rebrand-sign-in-screen-on-budget)

This PR aims to rebrands the Money Navigator and Budget Planner registration pages:
- Register page;
- Forgot your password page;
- Sign-in page.

This was achieved by using the existing NTT stylesheets with minor additions for some input types.

Terms & Conditions and Privacy links / copy was also updated.

This PR also rebases the `feature/NTT_Rebased` branch with `master`.

### CODE REVIEW

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/12006

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/12007

**Comment by jordanlg27** [comment]
https://maps.tpondemand.com/entity/12005

**Comment by davidtrussler** [comment]
@andreferreiradlw This PR appears to add a good deal of stuff that's irrelevant for the particular tasks it is dealing with. Could we take that out otherwise it becomes a bit confusing? This may be more urgent given that some of the code that is added here has been removed from the deployed state of frontend so we don't want to risk accidentally reinstating it!

**Comment by andreferreiradlw** [comment]
I'll open a new PR without rebasing with the master branch.

**Pull request closed without merging**
