### PR TITLE
bump up cost calclator builder version to 0.1.6

### PR DESCRIPTION
**Pull request by rnalexander**

### CODE REVIEW

**Comment by darokel** [comment]
You need to run bundle so it updates the `Gemfile.lock`

**Comment by Tr4pSt3R** [comment]
Run ```bundle update cost_calculator_builder``` so that it updates just the gem you need and its dependencies.

**Comment by rnalexander** [comment]
knew I was forgetting something.  ggaaah.  too out of practice.

**Comment by darokel** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:+1:

**Pull request merged**
