### PR TITLE
[DEV APPROVED] 9101 Universal Credit test support

### PR DESCRIPTION
**Pull request by margOnline**
[TP 9101](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9101)

**Summary**
Adds support files for the money manager end to end tests.

**Description**
The money manager feature specs test that the user is directed to the correct view dependant on whether or not he is signed in and has saved a questionnaire. The tests for this functionality belong in the universal credit repo where the code the code for that functionality lives. This pr addresses the issue of lack of cassettes for the devolved nations. 

Moving these specs to the universal_credit repo is documented in this [card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&boardPopup=userstory/9137).

**QA / Testing**
No testing is required as there is no functional change. The additional files are purely support for the tests.

**Checklist**

Make sure that when your PR is good to be reviewed you check the below checks:

+ [x] Tests passed.
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Code Climate passed for this PR.
+ [x] Commit history reviewed (clear commit messages).

### CODE REVIEW

**Comment by tomas-stefano** [comment]
There are some cassettes recorded as 404 http status. Are the tests supposed to pass when those return 404?

**Comment by margOnline** [comment]
@willhall88 @tomas-stefano @Tr4pSt3R updated description and cassettes ♻️

**Comment by Tr4pSt3R** [comment]
@margOnline it needs to be rebased with the master branch. All else looks good.

**Comment by margOnline** [comment]
thx @Tr4pSt3R done!

**Pull request merged**
