### PR TITLE
Bumping version of budget planner

### PR DESCRIPTION
**Pull request by slaywell**

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
Hi @slaywell if it is a minor change then bump it as, ```4.0.3```? Here: https://github.com/moneyadviceservice/budget_planner/blob/master/lib/budget_planner/version.rb#L5

**Comment by slaywell** [comment]
@Tr4pSt3R Have done, how's that looking now?

**Comment by Tr4pSt3R** [comment]
@slaywell niceee. Do you know how to squash commits? So that we can combine these two commits into one.
Bumping version of budget planner & Updating version number to next patch

**Comment by slaywell** [comment]
Have done @Tr4pSt3R - how's that now?

**Comment by johnplayer1982** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
@slaywell oh wow! Nice :dancer: :dancers: :dango: 

Let's deploy!
:+1:

**Pull request merged**
