### PR TITLE
[DEV APPROVED] 7973 - Remove "directory" block from home page, campaign and error page

### PR DESCRIPTION
**Pull request by jongilbraith**
Edited: removed blurb about tidying of css, instead now everything's been removed.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1674)

### CODE REVIEW

**Comment by jongilbraith** [comment]
Pinging @slaywell for the css refactor...

**Comment by slaywell** [comment]
Looks good, but as discussed - let's find out if this is supposed to be removed everywhere (if so there's a load more CSS we can delete).

**Comment by jongilbraith** [comment]
Confirmed we don't want the directory on any pages now, so have removed it all.

**Comment by Tr4pSt3R** [comment]
@jongilbraith it looks like most of the tools and the styleguide are using the 'shared/directory'. See below:

```
 () ~/Projects/MAS/frontend (7973-remove-home-page-categories)
⤷  ack 'shared/directory'
app/views/layouts/engine.html.erb
25:          <%= render 'shared/directory',

app/views/styleguide/components_website.html.erb
51:  <%= render 'shared/directory',

app/views/styleguide/pages_campaign.html
77:    <%= render 'shared/directory', items: category_navigation, heading_level: 4 %>

app/views/styleguide/pages_tool.html.erb
28:      <%= render 'shared/directory',
```

**Comment by slaywell** [comment]
Hey @jongilbraith I think you also need to remove any `display_category_directory` methods in controllers, and also the conditional block on the `engine.html.erb` view. At the moment I'm getting an error when trying to load /en/tools/house-buying/stamp-duty-calculator

**Comment by Tr4pSt3R** [comment]
👍 👍

**Comment by jongilbraith** [comment]
👍 

@slaywell @Tr4pSt3R thanks for catching the shoddy workmanship in my rather careless PR.

**Comment by Tr4pSt3R** [comment]
@jongilbraith it's a rarity. #dodobird

**Pull request merged**
