### PR TITLE
[DEV APPROVED]7628 - On-Page Feedback component

### PR DESCRIPTION
**Pull request by tomas-stefano**
## What?

This PR adds the new On-Page Feedback component. This appears on every article and is intended to allow us to capture better feedback when users do not find an article helpful. Also it promotes social sharing for when they _do_ find it helpful.

## How does it work?

This appears on every article page. It has a 'thumbs up' and a 'thumbs down' button. When the user clicks either this sends an AJAX request (POST) to the CMS which notes the interaction and returns the total likes / dislikes. Depending on whether it was a positive or a negative interaction the user is then asked to share the page or enter a comment. This sends another AJAX request (PATCH) to the CMS to log the share / comment.

Visual demo:

http://g.recordit.co/HIYtPEuq0Q.gif

## Anything else?

There will be some extra features added to this component around security and tracking but this is in an MVP state, and this PR is big enough already so we are putting it up for review.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1563)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
There is one duplication reported by Code Climate that IMHO should be ignored. But if you're reviewing and have a suggestion I appreciate. The PR is free to be reviewed now.

**Comment by rnalexander** [comment]
There's also a Hakiri warning popping up, can you check it out @tomas-stefano ?

**Comment by tomas-stefano** [comment]
@rnalexander there is one haikiri but it is not related to this PR. It is an existent warning.

**Comment by tomas-stefano** [comment]
And this warning is a false positive too.

**Comment by jongilbraith** [comment]
A lot to consider, but nothing jumping out at me as problematic. So 👍

**Comment by rnalexander** [comment]
LGTM, keep in mine I was less able to deeply review in general due to size, and couldn't put as strong a gaze on the frontend stuff.

:+1: :shipit:

**Pull request merged**
