### PR TITLE
[DEV APPROVED] fix expectation test for Sticky newsletter

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1420)

### CODE REVIEW

**Comment by davidtrussler** [comment]
:+1:

**Comment by jongilbraith** [comment]
Right, have now had a proper look at this as I was the last one to work on this.

So, the steps don't match up with the scenario description. I changed it so that it should just test the footer appearing, so the dismiss step should just not be in there.

If you want to actually test the dismissal, then we should add a new scenario for that.

**Comment by rnalexander** [comment]
:+1: Good catch.

**Comment by Tr4pSt3R** [comment]
@jongilbraith could you have another look please?

**Comment by jongilbraith** [comment]
@Tr4pSt3R excellent :smile:  :+1:

**Comment by rnalexander** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
Thanks @jongilbraith @rnalexander @davidtrussler

**Pull request merged**
