### PR TITLE
[DEV APPROVED]Remove references to feature toggles

### PR DESCRIPTION
**Pull request by margOnline**
Since we don't use feature toggles, the corresponding gem and config files are redundant.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1723)

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@margOnline shall we delete these files too please?

`config/features.yml`
`config/features.yml.sample`

**Comment by Tr4pSt3R** [comment]
Shall we remove this gem too, please? Maybe all the feature toggle should happen in one PR :)

In Gemfile
`gem 'feature'`

**Comment by tomas-stefano** [comment]
Good call! As we discussed, there is more places to remove: https://github.com/moneyadviceservice/frontend/blob/master/config/initializers/feature.rb & https://github.com/moneyadviceservice/frontend/blob/master/test.sh

**Comment by Tr4pSt3R** [comment]
👍

**Comment by tomas-stefano** [comment]
The tests were raising an odd error:

```
/Users/tomasdestefi/.rvm/gems/ruby-2.2.5@frontend/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': no implicit conversion of Pathname into String (TypeError)
```

The reason is the require on the core.rb initializer: https://github.com/moneyadviceservice/frontend/blob/master/config/initializers/core.rb#L6
Can you remove, please?

**Comment by jriga** [comment]
👍

**Comment by tomas-stefano** [comment]
👍

**Pull request merged**
