### PR TITLE
6940 content hub design prototype

### PR DESCRIPTION
**Pull request by davidtrussler**
This is to test the design of the new Content Hub area with static content.

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
woah!

**Comment by Tr4pSt3R** [comment]
Mr. @davidtrussler is there any chance of adding a gif image so that I can see what they look like please? I know I can run it locally but, blahh haha!

Good work Mr. Trussler :)

**Comment by davidtrussler** [comment]
@Tr4pSt3R Hang on - going to do this again ...

**Comment by Tr4pSt3R** [comment]
@davidtrussler @pmcostello delete this branch, if it's not needed?

**Pull request closed without merging**
