### PR TITLE
[DEV APPROVED] - Quiz authentication

### PR DESCRIPTION
**Pull request by tomas-stefano**
This is related to https://github.com/moneyadviceservice/quiz/pull/9

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@tomas-stefano i'm guessing these three commits will be squished into one?

**Comment by tomas-stefano** [comment]
Yes. I squashed into one.

**Comment by benbarnett** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
:100: :+1:

**Comment by tomas-stefano** [comment]
Thanks guys. Now I am waiting for the pipeline being unblocked. I changed to dev approved as @rnalexander asks on the channel.

**Comment by tomas-stefano** [comment]
@darokel can you review again please?

**Comment by darokel** [comment]
Awesome :+1: :ship:

**Pull request merged**
