### PR TITLE
Fix logging facade in old IE

### PR DESCRIPTION
**Pull request by stevoland**
Think I broke this with my first commit :/

### CODE REVIEW

**Comment by darokel** [comment]
@stevoland @benbarnett Status on this PR guys?

**Comment by stevoland** [comment]
@benbarnett @darokel Would like to get some thumbs on this. I need it merged as it's affecting my current story.

**Comment by benbarnett** [comment]
Here you go :+1:

**Comment by ourmaninamsterdam** [comment]
:+1:

**Pull request merged**
