### PR TITLE
[WIP] Document clean architecture

### PR DESCRIPTION
**Pull request by tomas-stefano**
I bring this commit from an old/stale branch and I think that is important to be documented on the Readme this clean architecture. Wdyt?

### CODE REVIEW

**Comment by darokel** [comment]
Good idea! Might be worth double checking whether we need to add more info

**Comment by tomas-stefano** [comment]
Until now, my actual knowledge is the same as this one list on the Readme. I double checked and I think I am not missing anything.

**Comment by tomas-stefano** [comment]
Is this good to go?

**Comment by darokel** [comment]
Not yet. What I meant was that we probably need to add some brief context underneath the heading of the core concepts. Specifically for Entities, Registries and Repositories

**Pull request closed without merging**
