### PR TITLE
[DEV APPROVED] Remove the debt management companies page.

### PR DESCRIPTION
**Pull request by misaka**
Work done originally by @jongilbraith. He also has a [branch in scripts](https://github.com/moneyadviceservice/scripts/tree/7025-remove-debt-management-companies-page) which creates redirects in the NGinx configs, but I believe these redirects belong in the CMS and my testing shows that they can be done there. Will confirm this in QA.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1443)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by misaka** [comment]
This will need the redirects setup in the CMS before deployment to production.

**Comment by slaywell** [comment]
👍

**Comment by misaka** [comment]
Now that this is dev approved I'm going to get it into QA for testing.

**Comment by UmairIft** [comment]
QA Approved 👍

**Pull request merged**
