### PR TITLE
[DEV APPROVED]Remove contact-us static page and accoutrements

### PR DESCRIPTION
**Pull request by misaka**
The goal is to allow contact-us to be handled by the CMS. The issue is
that this page is a lynch-pin for the machinery that serves out static
pages. Without it tests fail as there's nothing left to serve out, so
this change involves removing the static page machinery and the related
tests.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1468)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
👍

**Comment by tomas-stefano** [comment]
Double thumbs 👍 👍  (or triple if you count the above)

**Comment by jongilbraith** [comment]
Following an IRL chat with @misaka about this, suggestions are:

- split off removal of accessibility templates, which appear to be left over from 01d10297378bf9bb181d1e41650a7bc2881a4c80
- remove the`StaticPageController` and remaining related templates, given that the contact us page will now be pulled out of the CMS through the `Corporate` objects.

**Comment by misaka** [comment]
@jongilbraith Just about splitting off the removal of the accessibility templates ... if we make that a PR unto it's own, just getting rid of the templates, that seems a bit

**Comment by misaka** [comment]
Ugh. Wrong button. Damn the location of that "Close and comment" button.

**Comment by misaka** [comment]
New PR for accessibility templates: #1472

**Comment by misaka** [comment]
@jongilbraith @tomas-stefano I've updated this PR removing the deletion of the accessibility static templates (they are in #1472 now) and adding the deletion of the `StaticPagesController` and it's `show.html.erb` view. Did I miss anything? 😉

**Comment by jongilbraith** [comment]
LGTM 👍

**Comment by rnalexander** [comment]
:+1: :shipit:

**Comment by pmcostello** [comment]
👍 looks good

**Pull request merged**
