### PR TITLE
article menu layout fixes

### PR DESCRIPTION
**Pull request by Guntrisoft**
- ensure that width of left menu is the same as category pages on desktop
- remove strapline which shouldn't be in desktop left nav
- ensure that back to top link doesn't appear on desktop when in an article

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett @ourmaninamsterdam

**Comment by benbarnett** [comment]
:+1:

**Comment by ourmaninamsterdam** [comment]
:+1:

**Comment by Guntrisoft** [comment]
@benbarnett @ourmaninamsterdam sorry realised my change caused a display issue on mobile - made another alteration to ensure that menu on the articles at bottom of page on mobile has a full bleed 'back to top' row and then the menu is padding in left/right - which is the same as the category pages.

**Comment by benbarnett** [comment]
Cool, still looks good :+1:

**Comment by ourmaninamsterdam** [comment]
:+1:

**Pull request merged**
