### PR TITLE
port email anywhere validator from old site

### PR DESCRIPTION
**Pull request by asmega**
- dependent on https://github.com/moneyadviceservice/postcode_anywhere-email_validation/pull/3

### CODE REVIEW

**Comment by darokel** [comment]
I think there may be some overlap with this https://github.com/moneyadviceservice/frontend/blob/509bd65a3162cce51c108234cce97ff589d5c848/lib/validators/email.rb?

**Comment by asmega** [comment]
So there is! I'll append the dns validation option on the end of that validator then

**Comment by asmega** [comment]
@darokel i've now moved this to the email validator that was already present

**Comment by darokel** [comment]
:shipit: :shipit:

**Pull request merged**
