### PR TITLE
port 503 error page from public website

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by benbarnett** [comment]
Can we just serve up the new 500 page we made a month or two ago?

**Comment by asmega** [comment]
@benbarnett no, that page is dynamic. this error page is for when the application server is down so needs to be completely static

**Comment by benbarnett** [comment]
Agree but I think there is a static one somewhere. Bear with me.

**Comment by benbarnett** [comment]
Seems it's no longer with us.

:+1:

**Comment by Tr4pSt3R** [comment]
:100: :+1:

**Pull request merged**
