### PR TITLE
[update] cutback-calculator version to 0.9.27

### PR DESCRIPTION
**Pull request by Tr4pSt3R**

### CODE REVIEW

**Comment by Guntrisoft** [comment]
:+1:

**Comment by neoeno** [comment]
:+1:

**Comment by benlovell** [comment]
https://robots.thoughtbot.com/rubys-pessimistic-operator

**Comment by benlovell** [comment]
If your aim is to pin the version, pin the version. Otherwise you should use the pessimistic operator correctly.

**Comment by Tr4pSt3R** [comment]
@benlovell it needed a kick because it seemed as though it was picking up the latest changes, so bumped it to the definite version

**Pull request merged**
