### PR TITLE
Add missing locale keys news and news_link

### PR DESCRIPTION
**Pull request by Tr4pSt3R**

### CODE REVIEW

**Comment by darokel** [comment]
Looks good. I'd dump the `schema.rb` changes though as you didn't make edits to the db. :+1:

**Comment by benlovell** [comment]
Yep looks good, but as @darokel said, `schema.rb` doesn't need to be in here.

**Comment by Tr4pSt3R** [comment]
The schema file has now been removed

**Comment by benlovell** [comment]
Great :+1:  squash those two commits please and we're good to go.

**Comment by neoeno** [comment]
Looks good after squash :+1:

**Comment by neoeno** [comment]
As req. by @benlovell I'm going to take care of squashing/releasing this

**Comment by benlovell** [comment]
:heart: thanks!

**Pull request merged**
