### PR TITLE
[DEV APPROVED] Rename responsive prefix to frontend

### PR DESCRIPTION
**Pull request by tomas-stefano**
* 'Frontend' is the common word used on the puppet scripts.
Let's use one name on the puppet scripts and the application

You can see the scripts changes here: https://github.com/moneyadviceservice/scripts/pull/691

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1505)

### CODE REVIEW

**Comment by rnalexander** [comment]
Does this change going through need to sync with the script changes?

**Comment by misaka** [comment]
@rnalexander Yup, that's right, Tomas maybe didn't say it strongly enough, but these changes need to go hand-in-hand with the PR he mentioned (https://github.com/moneyadviceservice/scripts/pull/691)

**Comment by jongilbraith** [comment]
👍

**Comment by misaka** [comment]
:+1:

**Pull request merged**
