### PR TITLE
[DEV APPROVED] - 8865 remove old news article code

### PR DESCRIPTION
**Pull request by gotbadger**
[TP 8865](https://moneyadviceservice.tpondemand.com/entity/8865-remove-unused-news-article-code)

**Summary**
News articles are no longer used in frontend with `/en/news` being a redirect in production to a [standalone blog](https://www.moneyadviceservice.org.uk/blog/). 

This code hanging around was incurring technical debt making the changes to add `mas-cms-client` to frontend more difficult that they should be.

This PR removes all the unused code and removes references to news articles from a few other tests.

### CODE REVIEW

**Comment by willhall88** [comment]
does this file also need to go? 
https://github.com/moneyadviceservice/frontend/blob/master/public/news-sitemap.xml

**Comment by gotbadger** [comment]
@willhall88 maybe. Its still served from https://www.moneyadviceservice.org.uk/news-sitemap.xml but looks like it has contents that suggested it could go. Not knowing the code base that well I've tried to be fairly conservative in what I've removed, taking out files that i know are definitely not needed.

If you think this could go without any issue it can be removed. WDYT?

**Comment by willhall88** [comment]
I probably have as much knowledge as you to be honest! It was definitely a question of whether it was now redundant, rather than a statement. If it looks like we still need it then, I'm happy for it to remain in the codebase.

**Comment by tomas-stefano** [comment]
@gotbadger can you talk with Ed and raise that https://www.moneyadviceservice.org.uk/news-sitemap.xml and it is probably/potentially not used anymore, please?

**Pull request merged**
