### PR TITLE
[DEV APPROVED]Fix gemfile.lock

### PR DESCRIPTION
**Pull request by shaley91**
There was a change to the Gemfile.lock that
resulted in a few gems being upgraded without
meaning too.  This commit resets all gems back
to the correct versions

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1628)

### CODE REVIEW

**Comment by jongilbraith** [comment]
So how's this been done? Manual review of what was upgraded when you did the delete and rebundle?

**Comment by shaley91** [comment]
I reset it back to what it was at before I merged anything this morning.  Then I added my gem and bundled.

**Comment by jongilbraith** [comment]
👍

**Comment by rnalexander** [comment]
:+1: :shipit:

**Pull request merged**
