### PR TITLE
cms powers home page promo banner

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by darokel** [comment]
That feature flag in the yaml?

**Comment by asmega** [comment]
@darokel I've just updated the sample feature flags

**Comment by Tr4pSt3R** [comment]
:+1:

**Comment by Tr4pSt3R** [comment]
@asmega i'm guessing it's updated in the default, staging and production feature config files?

**Comment by asmega** [comment]
@Tr4pSt3R nope

**Comment by Tr4pSt3R** [comment]
@asmega oh that may need to be added then Doc

**Comment by asmega** [comment]
@Tr4pSt3R yes it will

**Comment by darokel** [comment]
:ship:

**Pull request merged**
