### PR TITLE
[DEV APPROVED] - TP: 7569, Comment: Updates element that has focus after search

### PR DESCRIPTION
**Pull request by davidtrussler**
This addresses an accessibility issue whereby the focus after a search returns to the top of the page rather than to the first result or, where there are no results, to the input field.

It is written as a Dough component so that it can be shared with the MAS blog to deal with the same issue. Depends on PR 275 in Dough (https://github.com/moneyadviceservice/dough/pull/275)

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1518)

### CODE REVIEW

**Comment by slaywell** [comment]
@davidtrussler I think this should go back to [WIP] status whilst the corresponding Dough PR is being worked on?

**Comment by davidtrussler** [comment]
@slaywell Yes, thanks for changing that. Also any idea if we need to be concerned about the failing check?

**Comment by slaywell** [comment]
I would ask @Tr4pSt3R about Hakiri - I don't think it's related to this PR specifically

**Comment by johnplayer1982** [comment]
Looks good, same implementation as the publify one :+1:

**Comment by slaywell** [comment]
👍  💯

**Comment by johnplayer1982** [comment]
:+1: for the additional commit

**Comment by slaywell** [comment]
Another 👍  from me

**Pull request merged**
