### PR TITLE
make crm calls asynchronous

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
@asmega it's failing on Code Climate but I can't jump on it to verify what's going on.

**Comment by tomas-stefano** [comment]
After seeing the code climate thing :+1: :+1:

**Comment by Tr4pSt3R** [comment]
@tomas-stefano what's the Code Climate issue about please?

**Comment by tomas-stefano** [comment]
I tried to login using github and I received 'You do not have permission to access that.'.

**Comment by asmega** [comment]
code climate is complaining about duplication with the 2 files being similar `lib/jobs/create_customer.rb` and `lib/jobs/update_customer.rb`

**Comment by Tr4pSt3R** [comment]
Oh Code Climate is really sharp and brilliant. 
It's not a major problem... :+1: :100:

**Comment by darokel** [comment]
:+1:

**Comment by pmcostello** [comment]
Sorry missed this yesterday, nice job Phil :+1:

**Pull request merged**
