### PR TITLE
[DEV APPROVED] Comment: Adds Optimizely tag to UAT

### PR DESCRIPTION
**Pull request by davidtrussler**
Depends on PR659 on Scripts repo (https://github.com/moneyadviceservice/scripts/pull/659)

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1480)

### CODE REVIEW

**Comment by jongilbraith** [comment]
👍

**Comment by misaka** [comment]
Just to mention, we're introducing the use of `ENV['MAS_ENVIRONMENT']` in cms, but using something more similar to how `Rails.env` works: https://github.com/moneyadviceservice/cms/pull/331/commits/f6d28d414a4fd6f98e26370aeb947a4e5c4768fc#diff-2787a0616bac77ec51a971ddb65c5d24R1

**Comment by misaka** [comment]
👍

**Comment by Tr4pSt3R** [comment]
👍

**Pull request merged**
