### PR TITLE
Put Welsh retirement landing pages behind feature flag.

### PR DESCRIPTION
**Pull request by neoeno**
I think this is going to take longer than I hoped to send live — this PR is so I don't block any of youse getting to production

@baphled @Tr4pSt3R since I think you're on the path to deployment

### CODE REVIEW

**Comment by neoeno** [comment]
Added another sneaky locales commit.

**Comment by munckymagik** [comment]
:+1:

**Comment by darokel** [comment]
Could you add this flag to the `features.yml.sample` too?

**Comment by neoeno** [comment]
@darokel Can do. What's the purpose of `features.yml.sample`? Are we supposed to have all feature flags enabled there?

**Comment by darokel** [comment]
@neoeno Because we don't check in the actual file, it's supposed to be a sourth of truth for all the features the application requires to run certain tools/sections. There's a command in the readme `cp config/features.yml.sample config/features.yml` which would copy over the most up to date features list to your local file. Not sure whether the values should be set to true by default though, this may bug out some specs.

**Comment by neoeno** [comment]
@darokel OK — noted & committed

**Comment by baphled** [comment]
Who do I bill for reading these ;D

**Comment by neoeno** [comment]
Ha, oops — sorry @baphled. Who was I trying to tag... can't remember...

**Comment by neoeno** [comment]
@asmega probably!

**Comment by baphled** [comment]
Haha @caden, s'all good, it's nice to be wanted :)

**Comment by mconnell** [comment]
:+1:

**Pull request merged**
