### PR TITLE
revert previous bump to debt_advice_locator tool 2.3.1 < 2.4.1

### PR DESCRIPTION
**Pull request by pmcostello**
ORIGINAL TP TICKET

https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=DDD7F3A626844AB8D1BEE3F06EC28EFA#page=board/4771110243071511547&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8188

THIS PR CHANGES THE VERSION OF THE DEBT ADVICE LOCATOR TOOL BACK TO PREVIOUS VERSION

TO FIX BUG INTRODUCED IN VERSION 2.4.1

### CODE REVIEW

**Comment by margOnline** [comment]
👍

**Comment by norm** [comment]
Y NO TP TICKET

But 👍 anyway

**Comment by willhall88** [comment]
If no TP ticket could we reference the PR that introduced the Bug please? I'm guessing that will have reference to a TP ticket in as well. 
no blocker 👍  anyway :)

**Comment by pmcostello** [comment]
@willhall88 good shout, I'll add the TP link for the original ticket to this PR

**Pull request merged**
