### PR TITLE
[DEV APPROVED] 9103 - Remove all Google site search code

### PR DESCRIPTION
**Pull request by tomas-stefano**
**Target Process ticket**

https://moneyadviceservice.tpondemand.com/entity/9103-frontend-check-for-removal-of-old

**Summary**

In doing the work to switch over the frontend from using google site search to Algolia we did not have a chance to properly survey the code and ensure that all of the google-search-specific code was not just de-activated but, in fact, fully removed from the site.  Both the Ruby and the Javascript codebases need to be audited for the now dead google-site-search code and have said code removed.

**Checklist**

Make sure that when your PR is good to be reviewed you check the below checks:

+ [x] Tests passed.
+ [x] Commit history reviewed (clear commit messages).

### CODE REVIEW

**Comment by willhall88** [comment]
I'm getting some errors 
```
  @javascript
  Scenario: Chat is online, advisors are available, and the user has JavaScript enabled # features/chat.feature:16
    Given chat is online                                                                # features/step_definitions/chat_steps.rb:1
```
```
One or more errors were raised in the Javascript code on the page. 
If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      Error: Script error for "googleComplete"
      http://requirejs.org/docs/errors.html#scripterror
      Error: Script error for "googleComplete"
      http://requirejs.org/docs/errors.html#scripterror
          at http://127.0.0.1:61075/assets/requirejs/require.js:141 in defaultOnError
          at http://127.0.0.1:61075/assets/requirejs/require.js:545 in onError
          at http://127.0.0.1:61075/assets/requirejs/require.js:1733 in onScriptError (Capybara::Poltergeist::JavascriptError)
      ./features/step_definitions/cookie_disclosure_steps.rb:20:in `/^I visit the website$/'
      ./features/step_definitions/chat_steps.rb:4:in `/^chat is online$/'
      ./features/support/env.rb:34:in `call'
      ./features/support/env.rb:34:in `block in <top (required)>'
      features/chat.feature:17:in `Given chat is online'
```

**Comment by osharpe** [comment]
`GOOGLE_API_GEO` is definitely required. Its in use by the `debt-advice-locator` tool.

**Comment by tomas-stefano** [comment]
@Tr4pSt3R thank you. I was talking last week with Oli about that because I needed to know what other env vars we were using and now that everything is clear, I can safely deleted.

**Comment by tomas-stefano** [comment]
@willhall88 this is strange. I have this issue on Friday morning and I fixed Friday morning and pushed.  Did you have the latest version? Everything green on my local machine. I will push to Go and see.

**Comment by tomas-stefano** [comment]
@willhall88 the tests passed here: https://go.dev.mas.local/go/tab/build/detail/responsive_commit_qa/358/test_and_build/1/test

**Comment by tomas-stefano** [comment]
@willhall88 ♻️

**Pull request merged**
