### PR TITLE
Make failing cucumber fail CI

### PR DESCRIPTION
**Pull request by neoeno**
Call cucumber directly to make it return a non-zero exit status.

Previously, running `test.sh` would run `rake cucumber`, which always returns a zero exit code (for some reason). This meant test failures wouldn't fail CI.

### CODE REVIEW

**Comment by neoeno** [comment]
NB: merging this will trigger a test failure on CI, because there are currently failing cukes.

**Comment by benlovell** [comment]
Ugh. Good catch. :+1:

**Comment by munckymagik** [comment]
If we do this, should we also remove `lib/tasks/cucumber.rake`? Do we know why it wasn't doing the right thing?

**Comment by benlovell** [comment]
Something somewhere in that chain might be handling `at_exit` and clobbering the real exit code. Maybe.

**Comment by asmega** [comment]
Merging #883 first should make the build pass

**Comment by neoeno** [comment]
#883 is merged, which means all the features should pass now.

However, I'm currently working on a different track on this, having observed some weird behaviour. Will check in here afterwards.

**Comment by neoeno** [comment]
OK, so I spent an inordinately long time working out what the root of this problem is. I think I have about 3/4 of it in my head now.

But basically — cucumber depends on minitest, which sets an `at_exit` hook, which interferes with Cucumber's exit code. The issue is only triggered by some line in the guts of DelayedJob (which is used by email_spec, which we use in `password_reset.feature`).

I've not been able to piece together precisely what's happening, but I know those three things are true.

So I wrote an alternative solution that allows us to keep the rake task as it currently works. Since we're not using Minitest, it should be harmless... but you can pick whichever solution you prefer.

**Comment by benlovell** [comment]
Yikes, so basically what I'd pointed out a few days ago... Good investigative work finding the exact root of it though! :+1:

**Comment by neoeno** [comment]
Ha! Fair point. But only some of the time...

Also, I noticed `newsletter_signup.feature` is still halting cucumber sometimes. At least now it should flag that as a failed build...

**Comment by asmega** [comment]
:+1:  nice work Sherlock

**Comment by munckymagik** [comment]
Crap, forgot to squash first. Soz :(

**Pull request merged**
