### PR TITLE
[DEV APPROVED] 8730 - Removes home buying checklist

### PR DESCRIPTION
**Pull request by thecountgs**
[TP# 8730](https://moneyadviceservice.tpondemand.com/entity/8730-removes-home-buying-checklist)

This PR removes the Home Buying Checklist beta code from our frontend branch.

## Solution

Remove `HomeBuyingChecklist.js` component
Remove call in `require_config.js.erb`
Remove view
Remove SCSS
Remove `home_buying_checklist_controller.rb`
Remove route
Remove all tests
Removes .yml files

 This code was a beta test for a tool that is being retired for possible future use. 

**Backup code in separate branch**
https://github.com/moneyadviceservice/frontend/tree/backup-home-buying-checklist

+ [x ] Tests passed.

---
This change is [Reviewable](https://reviewable.io/reviews/moneyadviceservice/frontend/1871)

### CODE REVIEW

**Comment by davidtrussler** [comment]
👍

**Comment by thecountgs** [comment]
@willhall88 I was thinking of making a separate ticket that updates the frontend readme with info on both glossary and home buying checklist and where their backup branches live. Does that sound good?

**Comment by willhall88** [comment]
@thecountgs I'm not familiar with the glossary code or it's removal, that has been done separately already? 

I think at the very least I would like more info to be put into the commit message here first. 

In terms of updating the readme, I would be tempted to also include the details of the home buying checklist into this commit so all details can be found through the same commit... however if there are a number of other changes to be made to the readme, then it is possibly better as a separate PR.

**Comment by tomas-stefano** [comment]
@thecountgs and @willhall88 I would suggest include the backup branch information on the commit message and on the README as well. IMHO should be on this PR.

**Comment by thecountgs** [comment]
@willhall88 @tomas-stefano 
I'll include the branch info in the commit message and update readme within this PR as-well per your request. I'll also remove the locales as requested.

**Comment by thecountgs** [comment]
@willhall88 @tomas-stefano I've removed the .yml files associated with the tool as well as amended the commit message and PR documentation as requested. It has been determined the update to the frontend readme file will be part of a separate PR that will include the glossary tooltips readme update as-well.

**Comment by Tr4pSt3R** [comment]
@thecountgs rebase your branch with master before merging please

**Comment by thecountgs** [comment]
@Tr4pSt3R Rebased sir.

**Comment by johnplayer1982** [comment]
Great bit of stripping out :+1:

**Pull request merged**
